name: Build PHAR

on:
  push: { }

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Install dependencies
        run: composer install --optimize-autoloader

      - name: Compile PHAR
        run: vendor/bin/box compile

      - name: Create GitHub Release and upload PHAR
        uses: softprops/action-gh-release@v1
        with:
          files: artisan.phar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
